global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'sql_exporter_pg_stat'
    static_configs:
      - targets: ['sql_exporter:9237']