global:
  scrape_timeout_offset: 500ms

target:
  data_source_name: "postgresql://admin:admin@localhost:5432/postgres?sslmode=disable"
  collectors:
    - pg_database_size
    - pg_stat_statements_summary

collectors:
  pg_database_size:
    metrics:
      - metric_name: pg_database_size_bytes
        type: gauge
        help: "Disk space used by each database"
        values:
          - value: size
            labels: [datname]
        query: |
          SELECT datname, pg_database_size(datname) AS size
          FROM pg_database
          WHERE datistemplate = false;

  pg_stat_statements_summary:
    metrics:
      - metric_name: pg_stat_statements_calls_total
        type: counter
        help: "Number of times each query was executed"
        values:
          - value: calls
            labels: [queryid, datname, short_query]
      - metric_name: pg_stat_statements_total_time_milliseconds
        type: counter
        help: "Total time spent on each query"
        values:
          - value: total_time
            labels: [queryid, datname, short_query]
      - metric_name: pg_stat_statements_min_time_milliseconds
        type: gauge
        help: "Minimum execution time"
        values:
          - value: min_time
            labels: [queryid, datname, short_query]
      - metric_name: pg_stat_statements_max_time_milliseconds
        type: gauge
        help: "Maximum execution time"
        values:
          - value: max_time
            labels: [queryid, datname, short_query]
      - metric_name: pg_stat_statements_mean_time_milliseconds
        type: gauge
        help: "Mean execution time"
        values:
          - value: mean_time
            labels: [queryid, datname, short_query]
        query: |
          SELECT
            queryid::text,
            datname,
            LEFT(query, 100) AS short_query,
            SUM(calls) AS calls,
            SUM(total_time) AS total_time,
            MIN(min_time) AS min_time,
            MAX(max_time) AS max_time,
            ROUND(SUM(mean_time * calls) / NULLIF(SUM(calls), 0), 2) AS mean_time
          FROM pg_stat_statements
          JOIN pg_database ON pg_stat_statements.dbid = pg_database.oid
          WHERE queryid IS NOT NULL
          GROUP BY queryid, short_query, datname;
