{
 "title": "PostgreSQL Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Количество запросов в секунду (RPS) для всего хранилища",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нагрузка на базу в целом (transactions/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[1m]) + rate(pg_stat_database_xact_rollback[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее число возвращённых строк (TOP 5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, pg_stat_statements_rows_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество вызовов SQL-запросов (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls_total[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения SQL-запросов (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_seconds_total[1m]) / rate(pg_stat_statements_calls_total[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(pg_stat_statements_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " I/O нагрузка по диску (общее время чтения/записи)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_block_read_seconds_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(pg_stat_statements_block_write_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование индексов (количество сканов) по индексам (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (indexname) (rate(pg_stat_user_tables_idx_scan[1m]))",
     "legendFormat": "{{indexname}}"
    }
   ]
  }
 ]
}