DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='admin') THEN
    CREATE ROLE admin
      WITH LOGIN
           PASSWORD '${PATRONI_POSTGRESQL_SUPERUSER_PASSWORD}'
           SUPERUSER
           CREATEDB;
  END IF;

  ALTER ROLE postgres WITH PASSWORD '${PATRONI_POSTGRESQL_SUPERUSER_PASSWORD}';

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='replicator') THEN
    CREATE ROLE replicator
      WITH LOGIN
           PASSWORD '${PATRONI_POSTGRESQL_REPLICATION_PASSWORD}'
           REPLICATION;
  END IF;
END;
$$;
